# If you are flashing via the pin header, you MUST remove MH-Z19 before flashing over serial or it will fail to flash
# If you are flashing over WiFi or USB-C, it will flash OK without removing the sensor.
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: recommended

esphome:
  name: co2home-2
  platformio_options:
    board_build.flash_mode: dio # If you don't specify this using esp-idf framework, the device will boot-loop.

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "co2home Fallback"
    password: "co2home123"

captive_portal:

# Enable logging
logger:
  # Use the ESP32-C3-MINI's native USB port for serial logging. Comment this out if you want to use the pin header.
  # Seems buggy.
  hardware_uart: USB_SERIAL_JTAG
  
  # Set baud_rate to 0 to disable logging. It can conflict with the sensor if done over UART.
  # Does not affect logging over WiFi.
  #baud_rate: 0


# Enable Home Assistant API
api:

# Enable OTA updates
ota:

uart:
  rx_pin: 4
  tx_pin: 5
  baud_rate: 9600

sensor:
  - platform: mhz19
    co2:
      name: "CO2home Value"
    temperature:
      name: "CO2home Temperature"
    update_interval: 60s
    #automatic_baseline_calibration: true