# You MUST remove MH-Z19 before flashing over serial or it will fail to flash
esphome:
  name: co2home
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "yourwifi"
  password: "yourpassword"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "co2home Fallback"
    password: "co2home123"

captive_portal:

# Enable logging
logger:
  baud_rate: 0
# Enable Home Assistant API
api:

ota:
uart:
  rx_pin: 3
  tx_pin: 1
  baud_rate: 9600

sensor:
  - platform: mhz19
    co2:
      name: "CO2home Value"
    temperature:
      name: "CO2home Temperature"
    update_interval: 60s
    #automatic_baseline_calibration: true